# Generated by Django 3.2.25 on 2024-12-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('place_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
        ),
    ]
