# Generated by Django 3.2.25 on 2024-12-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profileavailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileavailability',
            old_name='place_name',
            new_name='place_id',
        ),
        migrations.RenameField(
            model_name='profileavailability',
            old_name='profile',
            new_name='profile_id',
        ),
    ]
