# Generated by Django 3.2.25 on 2024-12-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20241219_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileavailability',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='profileavailability',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
