version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TOMTOM_MAPS_API_KEY=${TOMTOM_MAPS_API_KEY}
      - PLACE_SERVICE_URL=${PLACE_SERVICE_URL}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000/api/
    depends_on:
      - app

volumes:
  dev-db-data:
  dev-static-data:
