# Generated by Django 3.2.25 on 2025-06-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneravailability',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.dog'),
        ),
        migrations.AlterField(
            model_name='owneravailability',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.owner'),
        ),
    ]
