# Generated by Django 3.2.25 on 2025-06-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20250623_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dog_pictures/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_pictures/'),
        ),
    ]
