# Generated by Django 3.2.25 on 2024-12-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='profile',
        ),
    ]
